# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iF3hlXQJR8TOwhGkBJi7rVCfX99yTBCpOBQZ9wEBoUQQ1YVbfVVIku6GdSK2N89sdEIaQPz+Knl1pDmJpmtrjay7p3rLG2mtrB5n6km3wAG9D2AsET18uklSYf/X3T1we8/INZWWTBbc6rYnBGVQxDeoDJ+bydEf4eUTHSKdnI5J1zuJuGZARz7hjJHSmYYunTBPF91TkzMhDDFliglw5rKflc9/5qSJBwGrS4v6a9wCy9qypfWeiS29Rfi3QbXz2M08ndvu6LQ8z2DCjxjwxBzVvwPQ4LoytICLETf9crpooaiWOOtP8Fs83YVl1HVQIRV5y1RqeDd3yLeLLANruz1/YUy+oFtmO3kKXzvZPQI6+bVi9TI+dLw7pGpmbc5bj93DtzDVcnldhHvHK/lCgsmAnLKBuyEAAwwGTPdWbqtoFXZ+C6za65yw+Q8V+JJeOTli03tXAyYbXlrd7hFtLLu3OD/NkEX5S2bMwptdBQfSdQVki/728r4YaFdPRNH88ztlcuFRYHQGVi54GY8MHrJ/vrSrBfZ09hXFmTAFegTbLzPcKhk4/adblNgwgTWh5VVC1IbmuafS+EWD6L+P5Xk8dcoc9ofXR4IziVzBRrM/ThVeh0x2z9A0BZLrOwe7i3dZrbDnRHaHeHbfczj3OdbkqlqtGypwStKnnpWhyYA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml